apiVersion: v1
kind: ConfigMap
metadata:
  name: waf-config
  namespace: azora-security
data:
  rules.conf: |
    # SQL Injection Protection
    SecRule ARGS "@detectSQLi" \
      "id:1001,phase:2,deny,status:403,msg:'SQL Injection Detected'"
    
    # XSS Protection
    SecRule ARGS "@detectXSS" \
      "id:1002,phase:2,deny,status:403,msg:'XSS Attack Detected'"
    
    # Rate Limiting
    SecRule IP:REQUEST_COUNT "@gt 100" \
      "id:1003,phase:1,deny,status:429,msg:'Rate Limit Exceeded'"
    
    # Brute Force Protection
    SecRule IP:FAILED_LOGIN_COUNT "@gt 5" \
      "id:1004,phase:1,deny,status:403,msg:'Too Many Failed Attempts'"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: waf
  namespace: azora-security
spec:
  replicas: 2
  selector:
    matchLabels:
      app: waf
  template:
    metadata:
      labels:
        app: waf
    spec:
      containers:
      - name: modsecurity
        image: owasp/modsecurity-crs:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: waf-config
          mountPath: /etc/modsecurity/rules
      volumes:
      - name: waf-config
        configMap:
          name: waf-config

---
apiVersion: v1
kind: Service
metadata:
  name: waf
  namespace: azora-security
spec:
  selector:
    app: waf
  ports:
  - port: 80
    targetPort: 80
  type: ClusterIP
