version: '3.8'
services:
  postgres-primary:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: azora_production
      POSTGRES_USER: azora_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_REPLICATION_USER: replicator
      POSTGRES_REPLICATION_PASSWORD: ${REPLICATION_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgresql.conf:/etc/postgresql/postgresql.conf
      - ./pg_hba.conf:/etc/postgresql/pg_hba.conf
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U azora_admin -d azora_production"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres-replica:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: azora_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGUSER: azora_admin
    volumes:
      - postgres_replica_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    depends_on:
      - postgres-primary
    restart: unless-stopped

  postgres-backup:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: azora_production
      POSTGRES_USER: azora_admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./backups:/backups
      - ./backup-script.sh:/backup-script.sh
    depends_on:
      - postgres-primary
    command: /bin/bash -c "chmod +x /backup-script.sh && /backup-script.sh"
    restart: unless-stopped

volumes:
  postgres_data:
  postgres_replica_data: