import OpenAI from 'openai';
import dotenv from 'dotenv';

dotenv.config();

export class ElaraContentGenerator {
    private openai: OpenAI;

    constructor() {
        this.openai = new OpenAI({
            apiKey: process.env.OPENAI_API_KEY || 'sk-placeholder', // User needs to provide key
        });
    }

    async generateLesson(params: {
        course: string;
        module: string;
        topic: string;
        duration: number;
        level: string;
    }) {
        console.log(`Generating lesson for: ${params.topic}`);

        // If no API key, return mock data
        if (!process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY === 'sk-placeholder') {
            console.log('Using mock generation (No API Key provided)');
            return this.getMockLesson(params);
        }

        try {
            const prompt = `
        You are Elara, an expert educator creating a ${params.duration}-minute lesson.

        Course: ${params.course}
        Module: ${params.module}
        Topic: ${params.topic}
        Level: ${params.level}

        Generate a comprehensive lesson including:
        1. Introduction (hook the learner)
        2. Main content (explain concepts clearly)
        3. Code examples (practical, runnable)
        4. Practice exercises (3-5 exercises)
        5. Summary and next steps

        Format as JSON with: title, script, codeExamples, exercises, quiz
        `;

            const response = await this.openai.chat.completions.create({
                model: 'gpt-4-turbo',
                messages: [{ role: 'user', content: prompt }],
                response_format: { type: 'json_object' }
            });

            const content = response.choices[0].message.content;
            return content ? JSON.parse(content) : null;
        } catch (error) {
            console.error('Error generating lesson:', error);
            throw error;
        }
    }

    private getMockLesson(params: any) {
        return {
            title: `Understanding ${params.topic}`,
            script: `Welcome to this lesson on ${params.topic}. In this session, we will explore the fundamental concepts... [Mock Script Generated by Elara]`,
            codeExamples: [
                { language: 'python', code: `print("Hello, ${params.topic}!")` }
            ],
            exercises: [
                { question: "What is the main concept?", answer: "To understand " + params.topic }
            ],
            quiz: [
                { question: "True or False?", options: ["True", "False"], correct: 0 }
            ]
        };
    }

    async generateCourse(outline: any) {
        const lessons = [];

        for (const module of outline.modules) {
            for (const topic of module.topics) {
                const lesson = await this.generateLesson({
                    course: outline.title,
                    module: module.title,
                    topic: topic.title,
                    duration: topic.duration,
                    level: outline.level
                });

                lessons.push({
                    module: module.title,
                    topic: topic.title,
                    content: lesson
                });
            }
        }

        return lessons;
    }
}
