export interface Qualification {
  id: string
  name: string
  shortName?: string
  category: string
  level: string
  type: string
  country?: string
  issuingBody: string
  description: string
  duration?: string
  azrReward?: number
  verifiable: boolean
  recognizedIn?: string[]
  prerequisites?: string[]
}

export const qualificationsData: Qualification[] = [
  {
    id: "qual-mba",
    name: "Master of Business Administration",
    shortName: "MBA",
    category: "Business & Finance",
    level: "Master Level",
    type: "Degree",
    country: "International",
    issuingBody: "Various Universities",
    description: "Advanced business management degree covering strategy, finance, and leadership",
    duration: "2 years",
    azrReward: 10000,
    verifiable: true,
    recognizedIn: ["US", "UK", "Canada", "Australia", "EU"],
  },
  {
    id: "qual-phd",
    name: "Doctor of Philosophy",
    shortName: "PhD",
    category: "Academic Education",
    level: "Doctoral Level",
    type: "Degree",
    country: "International",
    issuingBody: "Research Universities",
    description: "Doctoral research degree in various disciplines",
    duration: "3-5 years",
    azrReward: 20000,
    verifiable: true,
    recognizedIn: ["Worldwide"],
  },
  {
    id: "qual-aws-cca",
    name: "AWS Certified Cloud Architect",
    shortName: "AWS-CCA",
    category: "Technology & IT",
    level: "Professional Certification",
    type: "Certification",
    country: "International",
    issuingBody: "Amazon Web Services",
    description: "Professional certification for designing distributed systems on AWS",
    duration: "3-4 months",
    azrReward: 5000,
    verifiable: true,
    recognizedIn: ["Worldwide"],
    prerequisites: ["AWS Solutions Architect Associate"],
  },
  {
    id: "qual-cissp",
    name: "Certified Information Systems Security Professional",
    shortName: "CISSP",
    category: "Technology & IT",
    level: "Professional Certification",
    type: "Certification",
    country: "International",
    issuingBody: "(ISC)²",
    description: "Leading cybersecurity certification for experienced professionals",
    duration: "6-12 months",
    azrReward: 8000,
    verifiable: true,
    recognizedIn: ["Worldwide"],
    prerequisites: ["5 years experience"],
  },
  {
    id: "qual-cpa",
    name: "Certified Public Accountant",
    shortName: "CPA",
    category: "Business & Finance",
    level: "Professional License",
    type: "License",
    country: "US",
    issuingBody: "AICPA & State Boards",
    description: "Professional accounting license required in the United States",
    duration: "4 years + exam",
    azrReward: 12000,
    verifiable: true,
    recognizedIn: ["US", "Canada"],
  },
  {
    id: "qual-md",
    name: "Doctor of Medicine",
    shortName: "MD",
    category: "Healthcare",
    level: "Doctoral Level",
    type: "Degree",
    country: "International",
    issuingBody: "Medical Schools",
    description: "Medical degree for practicing physicians",
    duration: "4 years + residency",
    azrReward: 25000,
    verifiable: true,
    recognizedIn: ["Most Countries"],
    prerequisites: ["Pre-med requirements"],
  },
  {
    id: "qual-ielts",
    name: "International English Language Testing System",
    shortName: "IELTS",
    category: "Languages",
    level: "Language Proficiency",
    type: "Test",
    country: "International",
    issuingBody: "British Council, IDP",
    description: "English proficiency test for study, work, and immigration",
    duration: "2 hours",
    azrReward: 2000,
    verifiable: true,
    recognizedIn: ["Worldwide"],
  },
  {
    id: "qual-pmp",
    name: "Project Management Professional",
    shortName: "PMP",
    category: "Business & Finance",
    level: "Professional Certification",
    type: "Certification",
    country: "International",
    issuingBody: "Project Management Institute",
    description: "Industry-leading project management certification",
    duration: "4-6 months",
    azrReward: 6000,
    verifiable: true,
    recognizedIn: ["Worldwide"],
    prerequisites: ["Project management experience"],
  },
  {
    id: "qual-jd",
    name: "Juris Doctor",
    shortName: "JD",
    category: "Legal",
    level: "Doctoral Level",
    type: "Degree",
    country: "US",
    issuingBody: "Law Schools",
    description: "Professional law degree for practicing attorneys",
    duration: "3 years",
    azrReward: 18000,
    verifiable: true,
    recognizedIn: ["US", "Some International"],
  },
  {
    id: "qual-comptia-security",
    name: "CompTIA Security+ Certification",
    shortName: "Security+",
    category: "Technology & IT",
    level: "IT Certification",
    type: "Certification",
    country: "International",
    issuingBody: "CompTIA",
    description: "Entry-level cybersecurity certification for IT professionals",
    duration: "2-3 months",
    azrReward: 3500,
    verifiable: true,
    recognizedIn: ["Worldwide"],
  },
  {
    id: "qual-gcse",
    name: "General Certificate of Secondary Education",
    shortName: "GCSE",
    category: "Academic Education",
    level: "Secondary Education",
    type: "Qualification",
    country: "UK",
    issuingBody: "Ofqual Exam Boards",
    description: "UK secondary school qualification covering academic subjects",
    duration: "2 years",
    azrReward: 1000,
    verifiable: true,
    recognizedIn: ["UK", "Commonwealth"],
  },
  {
    id: "qual-ba-cs",
    name: "Bachelor of Science in Computer Science",
    shortName: "B.Sc. CS",
    category: "Academic Education",
    level: "Undergraduate",
    type: "Degree",
    country: "International",
    issuingBody: "Universities",
    description: "Undergraduate degree in computer science fundamentals",
    duration: "4 years",
    azrReward: 8000,
    verifiable: true,
    recognizedIn: ["Worldwide"],
  },
]

export const categories = Array.from(new Set(qualificationsData.map((q) => q.category))).sort()

export const levels = Array.from(new Set(qualificationsData.map((q) => q.level))).sort()

export const countries = Array.from(
  new Set(
    qualificationsData
      .filter((q) => q.country)
      .map((q) => q.country)
      .filter(Boolean),
  ),
).sort()
