FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm ci --only=production

COPY prisma ./prisma
RUN npx prisma generate

COPY shared ./shared
COPY auth-service ./auth-service
COPY education-service ./education-service

EXPOSE 4002

CMD ["node", "education-service/index.js"]
