// student-portal API Configuration
// Generated by connect-frontends-backends.js

export const API_CONFIG = {
  BASE_URL: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:4002',
  BACKEND_SERVICE: 'azora-education',
  ENDPOINTS: {
    COURSES: '/api/courses',
    ENROLLMENT: '/api/enrollment',
    PROGRESS: '/api/progress'
  },
  HEALTH_CHECK: '/health',
  TIMEOUT: 30000,
  RETRY_ATTEMPTS: 3
};

export class studentportalApiClient {
  private baseUrl: string;
  
  constructor() {
    this.baseUrl = API_CONFIG.BASE_URL;
  }
  
  async get(endpoint: string) {
    const response = await fetch(`${this.baseUrl}${endpoint}`);
    return response.json();
  }
  
  async post(endpoint: string, data: any) {
    const response = await fetch(`${this.baseUrl}${endpoint}`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(data)
    });
    return response.json();
  }
  
  async healthCheck() {
    try {
      const response = await fetch(`${this.baseUrl}/health`);
      return response.ok;
    } catch {
      return false;
    }
  }
}

export const apiClient = new studentportalApiClient();
