import React, { useState, useEffect } from 'react';

interface Table {
  id: string;
  name: string;
  fields: Field[];
  relationships: Relationship[];
}

interface Field {
  id: string;
  name: string;
  type: string;
  nullable: boolean;
  primary: boolean;
  unique: boolean;
  defaultValue?: string;
}

interface Relationship {
  id: string;
  fromTable: string;
  toTable: string;
  fromField: string;
  toField: string;
  type: 'one-to-one' | 'one-to-many' | 'many-to-many';
}

const DatabaseDesigner: React.FC = () => {
  const [tables, setTables] = useState<Table[]>([]);
  const [selectedTable, setSelectedTable] = useState<Table | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);

  const addTable = () => {
    const newTable: Table = {
      id: `table-${Date.now()}`,
      name: 'NewTable',
      fields: [
        {
          id: `field-${Date.now()}`,
          name: 'id',
          type: 'INTEGER',
          nullable: false,
          primary: true,
          unique: true
        }
      ],
      relationships: []
    };
    setTables([...tables, newTable]);
    setSelectedTable(newTable);
  };

  const addField = (tableId: string) => {
    const newField: Field = {
      id: `field-${Date.now()}`,
      name: 'new_field',
      type: 'VARCHAR(255)',
      nullable: true,
      primary: false,
      unique: false
    };
    
    setTables(tables.map(table => 
      table.id === tableId 
        ? { ...table, fields: [...table.fields, newField] }
        : table
    ));
  };

  const updateField = (tableId: string, fieldId: string, updates: Partial<Field>) => {
    setTables(tables.map(table => 
      table.id === tableId 
        ? {
            ...table,
            fields: table.fields.map(field =>
              field.id === fieldId ? { ...field, ...updates } : field
            )
          }
        : table
    ));
  };

  const deleteField = (tableId: string, fieldId: string) => {
    setTables(tables.map(table => 
      table.id === tableId 
        ? {
            ...table,
            fields: table.fields.filter(field => field.id !== fieldId)
          }
        : table
    ));
  };

  const generatePrismaSchema = async () => {
    setIsGenerating(true);
    
    let schema = `// Generated by AzStudio Database Designer
generator client {
  provider = "prisma-client-js"
}

datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

`;

    tables.forEach(table => {
      schema += `model ${table.name} {\n`;
      
      table.fields.forEach(field => {
        let fieldLine = `  ${field.name} ${field.type}`;
        
        if (field.primary) fieldLine += ' @id';
        if (field.unique && !field.primary) fieldLine += ' @unique';
        if (!field.nullable && !field.primary) fieldLine += ' @default(now())';
        if (field.defaultValue) fieldLine += ` @default(${field.defaultValue})`;
        
        schema += fieldLine + '\n';
      });
      
      // Add relationships
      table.relationships.forEach(rel => {
        const targetTable = tables.find(t => t.id === rel.toTable);
        if (targetTable) {
          schema += `  ${rel.fromField} ${targetTable.name} @relation\n`;
        }
      });
      
      schema += '}\n\n';
    });

    // Send to AI assistant for review
    if (window.electronAPI?.fs?.writeFile) {
      await window.electronAPI.fs.writeFile('schema.prisma', schema);
    }
    
    setIsGenerating(false);
    
    // Show in AI assistant
    const aiPanel = document.querySelector('.ai-messages');
    if (aiPanel) {
      const message = document.createElement('div');
      message.className = 'ai-message assistant';
      message.innerHTML = `
        <strong>🗄️ Prisma Schema Generated!</strong><br>
        <pre style="background: #2d2d2d; padding: 12px; border-radius: 4px; overflow-x: auto; font-size: 12px;">${schema}</pre>
        <br>
        ✅ Schema saved to <code>schema.prisma</code><br>
        🚀 Ready for <code>prisma migrate dev</code>
      `;
      aiPanel.appendChild(message);
    }
  };

  const renderTable = (table: Table) => (
    <div
      key={table.id}
      className={`database-table ${selectedTable?.id === table.id ? 'selected' : ''}`}
      onClick={() => setSelectedTable(table)}
      style={{
        border: '2px solid #007acc',
        borderRadius: '8px',
        padding: '12px',
        margin: '8px',
        background: '#252526',
        cursor: 'pointer',
        minWidth: '200px'
      }}
    >
      <h4 style={{ margin: '0 0 8px 0', color: '#007acc' }}>{table.name}</h4>
      
      {table.fields.map(field => (
        <div
          key={field.id}
          style={{
            padding: '4px 8px',
            margin: '2px 0',
            background: field.primary ? '#007acc20' : 'transparent',
            borderRadius: '4px',
            fontSize: '12px',
            color: '#cccccc'
          }}
        >
          <span style={{ color: field.primary ? '#007acc' : '#cccccc' }}>
            {field.name}
          </span>
          <span style={{ color: '#8c8c8c', marginLeft: '8px' }}>
            {field.type}
          </span>
          {field.primary && <span style={{ color: '#007acc', marginLeft: '4px' }}>🔑</span>}
          {field.unique && <span style={{ color: '#ffcc02', marginLeft: '4px' }}>🔒</span>}
        </div>
      ))}
      
      <button
        onClick={(e) => {
          e.stopPropagation();
          addField(table.id);
        }}
        style={{
          marginTop: '8px',
          padding: '4px 8px',
          background: '#007acc',
          color: 'white',
          border: 'none',
          borderRadius: '4px',
          cursor: 'pointer',
          fontSize: '11px'
        }}
      >
        + Add Field
      </button>
    </div>
  );

  return (
    <div style={{ padding: '16px', height: '100%', overflow: 'auto' }}>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '16px' }}>
        <h3 style={{ margin: 0, color: '#007acc' }}>🗄️ Database Schema Designer</h3>
        <div>
          <button
            onClick={addTable}
            style={{
              padding: '8px 16px',
              background: '#007acc',
              color: 'white',
              border: 'none',
              borderRadius: '4px',
              cursor: 'pointer',
              marginRight: '8px'
            }}
          >
            + Add Table
          </button>
          <button
            onClick={generatePrismaSchema}
            disabled={tables.length === 0 || isGenerating}
            style={{
              padding: '8px 16px',
              background: isGenerating ? '#666' : '#28a745',
              color: 'white',
              border: 'none',
              borderRadius: '4px',
              cursor: isGenerating ? 'not-allowed' : 'pointer'
            }}
          >
            {isGenerating ? '⚡ Generating...' : '🚀 Generate Prisma'}
          </button>
        </div>
      </div>

      <div style={{ display: 'flex', gap: '16px' }}>
        {/* Canvas Area */}
        <div style={{ flex: 1, background: '#1e1e1e', borderRadius: '8px', padding: '16px', minHeight: '400px' }}>
          {tables.length === 0 ? (
            <div style={{ textAlign: 'center', color: '#8c8c8c', padding: '40px' }}>
              <h4>No tables yet</h4>
              <p>Click "Add Table" to start designing your database schema</p>
            </div>
          ) : (
            <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
              {tables.map(renderTable)}
            </div>
          )}
        </div>

        {/* Properties Panel */}
        {selectedTable && (
          <div style={{ width: '300px', background: '#252526', borderRadius: '8px', padding: '16px' }}>
            <h4 style={{ margin: '0 0 16px 0', color: '#007acc' }}>Table Properties</h4>
            
            <div style={{ marginBottom: '16px' }}>
              <label style={{ display: 'block', marginBottom: '4px', color: '#cccccc', fontSize: '12px' }}>
                Table Name
              </label>
              <input
                type="text"
                value={selectedTable.name}
                onChange={(e) => {
                  setTables(tables.map(table =>
                    table.id === selectedTable.id
                      ? { ...table, name: e.target.value }
                      : table
                  ));
                }}
                style={{
                  width: '100%',
                  padding: '8px',
                  background: '#2d2d2d',
                  border: '1px solid #3e3e3e',
                  color: '#cccccc',
                  borderRadius: '4px'
                }}
              />
            </div>

            <h5 style={{ margin: '0 0 8px 0', color: '#cccccc', fontSize: '14px' }}>Fields</h5>
            {selectedTable.fields.map(field => (
              <div key={field.id} style={{ marginBottom: '12px', padding: '8px', background: '#2d2d2d', borderRadius: '4px' }}>
                <input
                  type="text"
                  value={field.name}
                  onChange={(e) => updateField(selectedTable.id, field.id, { name: e.target.value })}
                  style={{ width: '100%', marginBottom: '4px', padding: '4px', background: '#1e1e1e', border: '1px solid #3e3e3e', color: '#cccccc', borderRadius: '2px' }}
                  placeholder="Field name"
                />
                <select
                  value={field.type}
                  onChange={(e) => updateField(selectedTable.id, field.id, { type: e.target.value })}
                  style={{ width: '100%', marginBottom: '4px', padding: '4px', background: '#1e1e1e', border: '1px solid #3e3e3e', color: '#cccccc', borderRadius: '2px' }}
                >
                  <option value="INTEGER">INTEGER</option>
                  <option value="VARCHAR(255)">VARCHAR(255)</option>
                  <option value="TEXT">TEXT</option>
                  <option value="BOOLEAN">BOOLEAN</option>
                  <option value="DATETIME">DATETIME</option>
                  <option value="DECIMAL(10,2)">DECIMAL(10,2)</option>
                </select>
                <div style={{ display: 'flex', gap: '8px' }}>
                  <label style={{ color: '#8c8c8c', fontSize: '11px' }}>
                    <input
                      type="checkbox"
                      checked={field.nullable}
                      onChange={(e) => updateField(selectedTable.id, field.id, { nullable: e.target.checked })}
                    /> Nullable
                  </label>
                  <label style={{ color: '#8c8c8c', fontSize: '11px' }}>
                    <input
                      type="checkbox"
                      checked={field.unique}
                      onChange={(e) => updateField(selectedTable.id, field.id, { unique: e.target.checked })}
                    /> Unique
                  </label>
                </div>
                <button
                  onClick={() => deleteField(selectedTable.id, field.id)}
                  style={{
                    marginTop: '4px',
                    padding: '2px 6px',
                    background: '#e81123',
                    color: 'white',
                    border: 'none',
                    borderRadius: '2px',
                    cursor: 'pointer',
                    fontSize: '10px'
                  }}
                >
                  Delete
                </button>
              </div>
            ))}
          </div>
        )}
      </div>
    </div>
  );
};

export default DatabaseDesigner;
