/*
AZORA PROPRIETARY LICENSE
Copyright © 2025 Azora ES (Pty) Ltd. All Rights Reserved.

CLIENT LIBRARY GENERATOR
Generates API client libraries for frontend consumption
*/

import { apiDocumentation } from './api-documentation';

/**
 * API Client Library Generator
 * Generates TypeScript client libraries for API consumption
 */
export class APIClientGenerator {
  /**
   * Generate TypeScript client for a service
   */
  async generateServiceClient(serviceName: string): Promise<string> {
    const doc = await apiDocumentation.generateServiceDocumentation(serviceName);

    const clientCode = `/*
AZORA PROPRIETARY LICENSE
Copyright © 2025 Azora ES (Pty) Ltd. All Rights Reserved.

Auto-generated API Client for ${serviceName}
Generated by Azora OS API Client Generator
*/

export class ${this.toPascalCase(serviceName)}Client {
  private baseUrl: string;
  private token?: string;

  constructor(baseUrl: string, token?: string) {
    this.baseUrl = baseUrl;
    this.token = token;
  }

  private async request(endpoint: string, options: RequestInit = {}): Promise<any> {
    const headers: HeadersInit = {
      'Content-Type': 'application/json',
      ...options.headers,
    };

    if (this.token) {
      headers['Authorization'] = \`Bearer \${this.token}\`;
    }

    const response = await fetch(\`\${this.baseUrl}\${endpoint}\`, {
      ...options,
      headers,
    });

    if (!response.ok) {
      throw new Error(\`API Error: \${response.status} \${response.statusText}\`);
    }

    return response.json();
  }

${doc.endpoints.map(e => this.generateEndpointMethod(e, serviceName)).join('\n\n')}
}

export default ${this.toPascalCase(serviceName)}Client;
`;

    return clientCode;
  }

  /**
   * Generate endpoint method
   */
  private generateEndpointMethod(endpoint: any, serviceName: string): string {
    const methodName = this.toCamelCase(endpoint.path.replace(/^\//, '').replace(/\//g, '_'));
    const method = endpoint.method.toLowerCase();

    return `  /**
   * ${endpoint.description}
   */
  async ${methodName}(params?: any): Promise<any> {
    return this.request('${endpoint.path}', {
      method: '${method}',
      ${method !== 'get' ? "body: JSON.stringify(params)," : ""}
    });
  }`;
  }

  /**
   * Convert to PascalCase
   */
  private toPascalCase(str: string): string {
    return str
      .split(/[-_\s]/)
      .map(word => word.charAt(0).toUpperCase() + word.slice(1).toLowerCase())
      .join('');
  }

  /**
   * Convert to camelCase
   */
  private toCamelCase(str: string): string {
    const pascal = this.toPascalCase(str);
    return pascal.charAt(0).toLowerCase() + pascal.slice(1);
  }
}

// Export singleton instance
export const apiClientGenerator = new APIClientGenerator();

export default apiClientGenerator;
