/*
AZORA PROPRIETARY LICENSE
Copyright (c) 2025 Azora ES (Pty) Ltd. All Rights Reserved.

DESIGN INFRASTRUCTURE BRIDGE - SNR DESIGNER'S RESPONSE TO ARCHITECT'S C4
This bridges design automation with infrastructure excellence
*/

import { designEngine } from './design-automation-engine'
import { AZORA_GEM_TOKENS } from '../../apps/azora-ui/lib/design-system/azora-gem-tokens'
import * as fs from 'fs/promises'
import * as path from 'path'

/**
 * 🌉 DESIGN INFRASTRUCTURE BRIDGE
 * 
 * Connects Design Automation Engine with Architect's Infrastructure
 * 
 * This bridge ensures:
 * 1. Design system scales with infrastructure
 * 2. Components work across all services
 * 3. Design tokens available infrastructure-wide
 * 4. Design compliance enforced at infrastructure level
 * 
 * @ubuntu Design infrastructure → Collective excellence
 */
export class DesignInfrastructureBridge {
  private infrastructureServices: string[] = []
  private designCompliance: Map<string, boolean> = new Map()

  /**
   * SCAN INFRASTRUCTURE: Find all services needing design integration
   */
  async scanInfrastructure(workspaceRoot: string = process.cwd()): Promise<string[]> {
    console.log('🌉 DESIGN INFRASTRUCTURE BRIDGE: Scanning infrastructure...')

    const servicesDir = path.join(workspaceRoot, 'services')
    const appsDir = path.join(workspaceRoot, 'apps')

    // Scan services
    try {
      const services = await fs.readdir(servicesDir)
      for (const service of services) {
        const servicePath = path.join(servicesDir, service)
        const stat = await fs.stat(servicePath)
        if (stat.isDirectory()) {
          this.infrastructureServices.push(`services/${service}`)
        }
      }
    } catch (error) {
      console.warn('Services directory not found')
    }

    // Scan apps
    try {
      const apps = await fs.readdir(appsDir)
      for (const app of apps) {
        const appPath = path.join(appsDir, app)
        const stat = await fs.stat(appPath)
        if (stat.isDirectory()) {
          this.infrastructureServices.push(`apps/${app}`)
        }
      }
    } catch (error) {
      console.warn('Apps directory not found')
    }

    console.log(`✅ Found ${this.infrastructureServices.length} infrastructure services`)
    return this.infrastructureServices
  }

  /**
   * DEPLOY DESIGN TOKENS: Make design tokens available infrastructure-wide
   */
  async deployDesignTokens(servicePath: string): Promise<void> {
    const tokensPath = path.join(servicePath, 'design-tokens.ts')
    const tokensContent = `/*
AZORA PROPRIETARY LICENSE
Copyright (c) 2025 Azora ES (Pty) Ltd. All Rights Reserved.

Auto-generated Design Tokens - Infrastructure Integration
Generated by Design Infrastructure Bridge
*/

// Re-export from central design system
export { 
  AZORA_GEM_COLORS,
  AZORA_GEM_TOKENS,
  SAPPHIRE_COLORS,
  EMERALD_COLORS,
  RUBY_COLORS,
  UBUNTU_COLORS,
  getGemColor,
  getUbuntuSpacing
} from '../../../apps/azora-ui/lib/design-system/azora-gem-tokens'

// Infrastructure-specific design tokens
export const INFRASTRUCTURE_DESIGN_TOKENS = {
  // Service-level spacing
  servicePadding: 'var(--space-ubuntu-lg)',
  serviceGap: 'var(--space-ubuntu-md)',
  
  // Infrastructure colors
  infrastructure: {
    primary: 'var(--sapphire-500)',
    secondary: 'var(--emerald-500)',
    accent: 'var(--ruby-500)',
  },
  
  // Infrastructure shadows
  serviceShadow: 'var(--shadow-lg)',
  serviceGlow: 'var(--glow-sapphire)',
}

export default INFRASTRUCTURE_DESIGN_TOKENS
`

    await fs.writeFile(tokensPath, tokensContent, 'utf-8')
    console.log(`✅ Design tokens deployed to ${servicePath}`)
  }

  /**
   * VALIDATE INFRASTRUCTURE DESIGN: Check all services for design compliance
   */
  async validateInfrastructureDesign(): Promise<InfrastructureDesignReport> {
    console.log('🔍 DESIGN INFRASTRUCTURE BRIDGE: Validating infrastructure design...')

    const report: InfrastructureDesignReport = {
      totalServices: this.infrastructureServices.length,
      compliantServices: 0,
      nonCompliantServices: [],
      complianceScore: 0,
      violations: [],
    }

    for (const service of this.infrastructureServices) {
      const servicePath = path.join(process.cwd(), service)
      
      // Check for design tokens
      const hasDesignTokens = await this.checkFileExists(
        path.join(servicePath, 'design-tokens.ts')
      )

      // Check for component usage
      const hasComponents = await this.findComponents(servicePath)

      // Validate components
      const violations = await designEngine.scanForViolations(servicePath)
      
      const isCompliant = hasDesignTokens && violations.length === 0
      
      if (isCompliant) {
        report.compliantServices++
        this.designCompliance.set(service, true)
      } else {
        report.nonCompliantServices.push({
          service,
          hasDesignTokens,
          hasComponents: hasComponents.length > 0,
          violations: violations.length,
        })
        this.designCompliance.set(service, false)
      }
    }

    report.complianceScore = (report.compliantServices / report.totalServices) * 100

    console.log(`✅ Infrastructure design validation complete`)
    console.log(`   Compliance: ${report.complianceScore.toFixed(1)}%`)
    console.log(`   Compliant: ${report.compliantServices}/${report.totalServices}`)

    return report
  }

  /**
   * GENERATE INFRASTRUCTURE COMPONENTS: Create infrastructure-aligned components
   */
  async generateInfrastructureComponent(
    serviceName: string,
    componentName: string,
    pillar: 'sapphire' | 'emerald' | 'ruby' | 'ubuntu'
  ): Promise<string> {
    const servicePath = path.join(process.cwd(), 'services', serviceName)
    const componentsDir = path.join(servicePath, 'components')
    
    // Ensure components directory exists
    await fs.mkdir(componentsDir, { recursive: true })

    const componentCode = `/*
AZORA PROPRIETARY LICENSE
Copyright (c) 2025 Azora ES (Pty) Ltd. All Rights Reserved.

Infrastructure Component - ${serviceName}
Generated by Design Infrastructure Bridge
${pillar.charAt(0).toUpperCase() + pillar.slice(1)} Pillar - Ubuntu Aligned
*/

import * as React from 'react'
import { getGemColor } from '../../../../apps/azora-ui/lib/design-system/azora-gem-tokens'
import { cn } from '@/lib/utils'

/**
 * ${componentName} - Infrastructure Component
 * 
 * @description Infrastructure-level component for ${serviceName}.
 *              Designed to scale with infrastructure excellence.
 * 
 * @ubuntu Infrastructure component → Collective system harmony
 * 
 * @infrastructure
 * - Scales with service architecture
 * - Integrates with infrastructure patterns
 * - Maintains design system compliance
 * 
 * @example
 * <${componentName} variant="${pillar}">
 *   Infrastructure Content
 * </${componentName}>
 */
export function ${componentName}({ 
  className,
  variant = '${pillar}',
  children,
  ...props 
}: React.HTMLAttributes<HTMLDivElement> & {
  variant?: 'sapphire' | 'emerald' | 'ruby' | 'ubuntu'
}) {
  const gemColor = getGemColor(variant === 'ubuntu' ? 'sapphire' : variant, '500')
  
  return (
    <div
      className={cn(
        'bg-[var(--${variant}-500)]',
        'text-white',
        'rounded-lg',
        'p-space-ubuntu-md',
        'transition-all',
        'duration-300',
        'hover:bg-[var(--${variant}-600)]',
        'focus-visible:ring-2',
        'focus-visible:ring-[var(--${variant}-500)]',
        'focus-visible:outline-none',
        'glow-${variant}',
        // Infrastructure-specific styling
        'shadow-lg',
        'border',
        'border-[var(--${variant}-500)]/20',
        className
      )}
      style={{
        '--gem-color': gemColor,
      } as React.CSSProperties}
      {...props}
    >
      {children}
    </div>
  )
}

export default ${componentName}
`

    const componentPath = path.join(componentsDir, `${componentName}.tsx`)
    await fs.writeFile(componentPath, componentCode, 'utf-8')
    
    console.log(`✅ Infrastructure component generated: ${componentPath}`)
    return componentPath
  }

  /**
   * CREATE INFRASTRUCTURE DESIGN CONFIG: Generate design config for service
   */
  async createInfrastructureDesignConfig(servicePath: string): Promise<void> {
    const configPath = path.join(servicePath, 'design.config.json')
    
    const config = {
      version: '1.0.0',
      service: path.basename(servicePath),
      designSystem: {
        tokens: '../../apps/azora-ui/lib/design-system/azora-gem-tokens',
        components: '../../apps/azora-ui/components/ui',
        css: '../../apps/azora-ui/globals.css',
      },
      compliance: {
        enabled: true,
        autoFix: true,
        validateOnBuild: true,
      },
      infrastructure: {
        scalable: true,
        microserviceReady: true,
        designTokensAvailable: true,
      },
      ubuntu: {
        philosophy: 'enforced',
        spacing: 'golden-ratio',
        colors: 'azora-gem',
      },
    }

    await fs.writeFile(configPath, JSON.stringify(config, null, 2), 'utf-8')
    console.log(`✅ Design config created: ${configPath}`)
  }

  /**
   * GENERATE INFRASTRUCTURE REPORT: Comprehensive infrastructure design report
   */
  async generateInfrastructureReport(outputPath: string): Promise<void> {
    const report = await this.validateInfrastructureDesign()
    
    const fullReport = {
      timestamp: new Date().toISOString(),
      infrastructure: {
        totalServices: report.totalServices,
        compliantServices: report.compliantServices,
        complianceScore: report.complianceScore,
        nonCompliantServices: report.nonCompliantServices,
      },
      designSystem: {
        tokensAvailable: true,
        componentsAvailable: true,
        ubuntuAlignment: 'enforced',
      },
      recommendations: this.generateInfrastructureRecommendations(report),
    }

    await fs.writeFile(outputPath, JSON.stringify(fullReport, null, 2), 'utf-8')
    console.log(`📊 Infrastructure design report generated: ${outputPath}`)
  }

  // Helper methods
  private async checkFileExists(filePath: string): Promise<boolean> {
    try {
      await fs.access(filePath)
      return true
    } catch {
      return false
    }
  }

  private async findComponents(servicePath: string): Promise<string[]> {
    try {
      const files = await fs.readdir(servicePath, { recursive: true })
      return files.filter(file => 
        file.endsWith('.tsx') || file.endsWith('.jsx')
      )
    } catch {
      return []
    }
  }

  private generateInfrastructureRecommendations(
    report: InfrastructureDesignReport
  ): string[] {
    const recommendations: string[] = []

    if (report.complianceScore < 80) {
      recommendations.push('Deploy design tokens to all services')
      recommendations.push('Run design automation engine on all services')
      recommendations.push('Create infrastructure design configs')
    }

    if (report.nonCompliantServices.length > 0) {
      recommendations.push('Fix design violations in non-compliant services')
      recommendations.push('Ensure all services use Azora Gem colors')
    }

    return recommendations
  }
}

// Types
interface InfrastructureDesignReport {
  totalServices: number
  compliantServices: number
  nonCompliantServices: NonCompliantService[]
  complianceScore: number
  violations: any[]
}

interface NonCompliantService {
  service: string
  hasDesignTokens: boolean
  hasComponents: boolean
  violations: number
}

// Export singleton
export const designInfrastructureBridge = new DesignInfrastructureBridge()

// CLI interface
if (require.main === module) {
  const bridge = new DesignInfrastructureBridge()
  const command = process.argv[2]

  switch (command) {
    case 'scan':
      bridge.scanInfrastructure().then(services => {
        console.log(`Found ${services.length} infrastructure services`)
        services.forEach(s => console.log(`  - ${s}`))
      })
      break

    case 'deploy':
      const service = process.argv[3]
      if (!service) {
        console.error('Usage: design-infrastructure-bridge.ts deploy <service-path>')
        process.exit(1)
      }
      bridge.deployDesignTokens(service).then(() => {
        console.log('✅ Design tokens deployed')
      })
      break

    case 'validate':
      bridge.validateInfrastructureDesign().then(report => {
        console.log(`Compliance Score: ${report.complianceScore.toFixed(1)}%`)
        console.log(`Compliant: ${report.compliantServices}/${report.totalServices}`)
      })
      break

    case 'report':
      bridge.scanInfrastructure()
        .then(() => bridge.generateInfrastructureReport('./infrastructure-design-report.json'))
        .then(() => console.log('✅ Infrastructure report generated'))
      break

    default:
      console.log(`
🌉 DESIGN INFRASTRUCTURE BRIDGE - SNR DESIGNER'S RESPONSE

Usage:
  scan              - Scan infrastructure services
  deploy <path>     - Deploy design tokens to service
  validate          - Validate infrastructure design
  report            - Generate infrastructure report

This bridges design automation with infrastructure excellence.
      `)
  }
}

export default designInfrastructureBridge
